services:
  web-services:
    container_name: web-app
    build:
      context: /app
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      db-services:
      condition:
        service-healthy
  db-services:
    container_name: db-app
    image: mysql:8.0
    volumes:
      db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=task_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  phpmyadmin:
    container_name: phpmyadmin-app
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST:db-services
      PMA_USER:${MYSQL_USER}
      PMA_PASSWORD:${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db-services 
    condition:
      service_healthy     

volumes:
  db_data:
       